Importando a biblioteca

Importando a biblioteca

In [1]:
import numpy as np 

Cria um array 

In [2]:
np.array([1, 2, 3 ])

array([1, 2, 3])

Criando um array de 0 em cinco posições

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

Essa função vez de colocar valor 0, ele coloca valor 1 

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

Essa terceira função ela cria um array os elementos terá valor aleatorio 

In [5]:
np.empty(10)

array([6.95332180e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       1.93101617e-312, 3.80132583e+175, 4.90464331e-062, 7.79078335e-091,
       5.70219451e-066, 8.74029144e-313])

Cria um array dentro de um intervalo especifico 

In [6]:
np.arange(4)

array([0, 1, 2, 3])

Definindo um intervalo especifico(Inclui o primeiro elemento, mas exclui o ultimo)

In [7]:
np.arange(1, 9, 2)

array([1, 3, 5, 7])

Separa os elemento limearmente, retornando quatro elementos

In [8]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Especifica o tipos de dados forçando certos valores

In [11]:
np.zeros(3, dtype=np.int64)

array([0, 0, 0])

Cria um array  e ordena os elementos

In [12]:
arr = np.array([12, 1, 5, 10, 3, 2, 7])

Salvando o array na variavel arr, chama a função a ordenação com nsort passando o array retornando outro array ordenado

In [13]:
np.sort(arr)

array([ 1,  2,  3,  5,  7, 10, 12])

Concatena dois array diferente

In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6]) 
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

Essa função trabalha com qualquer dimenção 

In [15]:
matriz = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    ])

Aqui ele irá retornar os valores guardados dentro da váriavel matriz

In [16]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Verifica quantas dimenções a estrutura no objeto

In [17]:
matriz.ndim

2

Verifica quantos atributos tem 

In [19]:
matriz.size

9

Esse atributo retorna qual o formato 

In [20]:
matriz.shape

(3, 3)

Trasforma essa matriz mudando o formato da estrutura

In [21]:
matriz.reshape(1, 9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

Pega qualquer matriz convertendo em uma linha ou columa 

In [22]:
a.shape

(3,)

Pega a estrutura e adiciona uma nova dimenção no objeto

In [23]:
a[np.newaxis, :]

array([[1, 2, 3]])

Mostrará o shape da nova estrutura 

In [26]:
a[np.newaxis, :].shape

(1, 3)