In [3]:
import numpy as np

In [5]:
a = np.array([10, 20, 30, 40, 50])
b = np.arange(5)

In [6]:
a

array([10, 20, 30, 40, 50])

In [7]:
b

array([0, 1, 2, 3, 4])

Fazendo operações diretas com arrays

In [8]:
a - b

array([10, 19, 28, 37, 46])

Resultado fazendo operações com elementos

In [35]:
a * 2

array([200,  40, 200,  80, 200])

In [36]:
b**2

array([ 0,  1,  4,  9, 16])

Aplicando operações logicas

In [37]:
a <= 30

array([False,  True, False, False, False])

Arrays com matrizes

In [38]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

In [39]:
A

array([[1, 1],
       [0, 1]])

In [40]:
B

array([[2, 0],
       [3, 4]])

Aplicando operações com os elementos das matrizes


In [41]:
A * B

array([[2, 0],
       [0, 4]])

In [42]:
A @ B

array([[5, 4],
       [3, 4]])

Combinando tecnicas, criando matrizes, visoes, view(filtros)

In [43]:
a

array([100,  20, 100,  40, 100])

In [44]:
a[2]

100

Pegando por intervalos

In [45]:
a[2:5]

array([100,  40, 100])

In [46]:
a[:5:2] = 100

In [47]:
a

array([100,  20, 100,  40, 100])

Formas para criar arrays(espaçamentos de memorias)

In [54]:
a

array([0, 1, 2, 3, 4])

In [55]:
b

array([0, 1, 2, 3, 4])

In [56]:
b = a

In [57]:
a

array([0, 1, 2, 3, 4])

In [58]:
b is a

True

Funções(identificador de objetos)

In [60]:
id(a)

139646438955888

In [61]:
id(b)

139646438955888

Criando copias

In [63]:
d = a.copy()

In [64]:
d

array([0, 1, 2, 3, 4])

In [65]:
d is a

False

In [66]:
d[0] = 200

In [67]:
d

array([200,   1,   2,   3,   4])

In [68]:
a

array([0, 1, 2, 3, 4])

In [69]:
b[0] = 300
a

array([300,   1,   2,   3,   4])